import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header-nav";
import Footer from "@/app/components/footer-nav";

export const metadata: Metadata = {
  title: "Title Text Here",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen p-8 flex flex-col">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
