import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/header-nav";
import Footer from "@/app/components/footer-nav";
import Spacer from "@/app/components/spacer";

export const metadata: Metadata = {
  title: "Title Text Here",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        {/* Ensure full height on the body */}
        <main className="min-h-screen px-8 flex flex-col">
          {" "}
          {/* Main container with flexbox */}
          <Header />
          <Spacer />
          <div className="flex-grow">{children}</div>{" "}
          {/* Make the child content grow */}
          <Footer />
        </main>
      </body>
    </html>
  );
}
